/* Textbook text is transcribed from the five user-provided photographs.
   Printed page numbers, not image filenames, are used throughout. */
const SOURCES = {
 '63-5': '5. Ты, конечно, любишь играть. Какие игрушки у тебя есть и сколько?',
 '63-9': '9. Посмотри на буквосочетание. Запомни, какой звук оно передаёт.\nwh [w]',
 '63-10': '10. Научись читать эти слова и предложения.\nwh [w]: what, What is his name? What is her name? What is he? He’s a pilot. What is she? She’s a doctor.\nwhere [weə]: Where is he from? Where is she from? Where is his family from? Where is her family from? Where is Sam from? He is from Africa. Where is Pam from? She is from America.\nwho [hu:]: Who is she? She is my sister. What is she? She is a pupil. Who is he? He is my brother. What is he? He is a doctor.',
 '64-11': '11. Составь 5 слов из данных букв. Напиши и прочитай их.\nw, a, m, n, y, e, n, A',
 '64-12': '12. Запомни, как пишутся эти слова.\nhave, what, where, who, family',
 '64-13': '13. Разгадай кроссворд.\n1. Сын моей мамы. 2. Каким коротким словом можно заменить слово «мальчик»? 3. Каким маленьким словом можно заменить слово «девочка»? 4. Вопросительное слово.',
 '64-rule': 'Множественное число существительных\nБольшинство существительных имеет два числа: единственное и множественное: a toy (игрушка) — toys (игрушки).\nМножественное число существительных образуется при помощи окончания -s или -es, которое произносится по-разному: [s], [z], [ɪz]. После глухих согласных — [s]: a cat — cats (кошки), после звонких согласных и гласных — [z]: a dog — dogs (собаки), после шипящих и свистящих — [ɪz]: a box — boxes (коробки).\nВо множественном числе неопределённый артикль a (an) перед существительными не употребляется.',
 '66-8': '8. Научись читать эти слова и предложения.\n[ɔ:]: or, your, daughter [ˈdɔ:tə], a daughter — daughters, cosmonaut [ˈkɔzmənɔ:t], a cosmonaut — cosmonauts, a sister or a brother, a son or a daughter, his daughter, He has got a daughter. His daughter is a doctor. Is he a pilot or a cosmonaut? He is a cosmonaut.\n[ɑ:]: are, father, grandfather, aunt, they are, we are, We are from Great Britain. Sam and Sally are from Africa; my father, My father is a pilot; his grandfather, Has he got a grandfather? Yes, he has; her aunt, Her aunt isn’t a driver, she is a doctor.',
 '66-9': '9. Спишите, вставляя пропущенные слова.\nI’ve got an aunt. … aunt is a doctor.\nYou’ve got a son. Is … son a pilot?\nShe has got a sister. … sister isn’t a pupil.\nyour, my, her',
 '67-10': '10. Запомни, как пишутся эти слова.\nand, yes, friend, hello, cosmonaut',
 '67-11': '11. Разгадай кроссворд.\n1. Профессия. 2. Кем приходится маме мой родной брат? 3. Вопросительное слово.',
 '67-rule': 'Образование утвердительной, вопросительной и отрицательной формы глагола are\nWe / You / They are pupils.\nAre we / you / they pupils?\nWe / You / They are not pupils.\nКраткие ответы\nYes, we / you / they are.\nNo, we / you / they are not.',
 '68-rule': 'Сокращённые формы\nWe are = We’re\nYou are = You’re\nThey are = They’re\nare not = aren’t',
 '68-3': '3. Расспросите друг друга, с чем и с кем вы любите играть.',
 '68-4': '4. Пригласи своего друга поиграть, побегать, попрыгать.'
};
const SEGMENTS = [
 ['login','AGENT LOGIN','Знакомство с агентом','0–5','Повторение',0],
 ['radio','RADIO ROOM','Восстанови связь','5–11','Presentation',0],
 ['inventory','INVENTORY LAB','Открой склад','11–17','Presentation',1],
 ['listen','RADIO SIGNAL','Поймай сигнал','17–24','Practice',0],
 ['sounds','SOUND SCANNER','Настрой сканер','17–24','Practice',1],
 ['team','TEAM FILES','Открой досье','24–30','Practice',2],
 ['break','TRAINING BREAK','Время подвигаться','30–33','Practice',2],
 ['code','CODE ROOM','Запусти оборудование','33–40','Practice',3],
 ['grammar','GRAMMAR GATE','Открой шлюз','40–45','Practice',3],
 ['production','BUILD YOUR TEAM','Твоя команда','45–55','Production',4],
 ['final','FINAL TRANSMISSION','Передай сообщение','55–60','Production',4]
].map(([id,title,ru,time,ppp,module])=>({id,title,ru,time,ppp,module}));
const MODULES = [{name:'RADIO',icon:'radio',label:'Связь'},{name:'INVENTORY',icon:'box',label:'Склад'},{name:'TEAM FILES',icon:'team',label:'Досье команды'},{name:'CODE ROOM',icon:'code',label:'Коды доступа'},{name:'FINAL',icon:'flag',label:'Финальная миссия'}];
const CROSSWORDS = {
 first:{rows:7,cols:5,words:[{n:1,r:0,c:3,dir:'down',word:'brother',clue:'Сын моей мамы.'},{n:2,r:4,c:3,dir:'across',word:'he',clue:'Каким коротким словом можно заменить слово «мальчик»?'},{n:3,r:5,c:1,dir:'across',word:'she',clue:'Каким маленьким словом можно заменить слово «девочка»?'},{n:4,r:6,c:0,dir:'across',word:'where',clue:'Вопросительное слово.'}]},
 second:{rows:9,cols:5,words:[{n:1,r:0,c:2,dir:'down',word:'cosmonaut',clue:'Профессия.'},{n:2,r:2,c:2,dir:'across',word:'son',clue:'Кем приходится маме мой родной брат?'},{n:3,r:6,c:0,dir:'across',word:'what',clue:'Вопросительное слово.'}]}
};
const TASKS=[];
function task(segment,type,title,data={}){TASKS.push({id:`${segment}-${TASKS.filter(t=>t.segment===segment).length+1}`,segment,type,title,author:true,...data});}
task('login','login','Welcome, agent!',{source:'63-5',prompt:'Выбери аватар и познакомься с учителем.',speech:'Welcome, agent! What’s your name? What toys have you got?',teacher:'What’s your name? What toys have you got? How many? Попросите назвать игрушки и их количество.',hint:'My name is… I’ve got two cars.'});
for(const [word,ipa,icon,text,note] of [
 ['what','/w/','🪪','What is his name? What is her name? What is he? He’s a pilot. What is she? She’s a doctor.','What — что? Какой? Спрашиваем об имени или профессии.'],
 ['where','/w/','🌍','Where is he from? Where is she from? Where is his family from? Where is her family from? Where is Sam from? He is from Africa. Where is Pam from? She is from America.','Where — где? Where … from? — откуда?'],
 ['who','/h/','👨‍👩‍👧','Who is she? She is my sister. What is she? She is a pupil. Who is he? He is my brother. What is he? He is a doctor.','Who — кто? Отдельное слово: начинается со звука /h/, а не /w/.']
]) task('radio','reading',`Meet ${word}`,{source:'63-10',author:false,word,ipa,icon,text,note,speech:`${word}. ${text}`,prompt:'10. Научись читать эти слова и предложения.',teacher:'Сначала LISTEN со скрытым текстом → открыть текст → прочитать вместе → повторить самостоятельно. Стр. 63, упр. 9: wh [w] применяем к what / where; who разбираем отдельно.'});
task('inventory','pairs','One → many',{source:'64-rule',prompt:'Один предмет или несколько?',pairs:[['🐈','a cat','cats','/s/'],['🐕','a dog','dogs','/z/'],['📦','a box','boxes','/ɪz/']],speech:'A cat. Cats. A dog. Dogs. A box. Boxes.',teacher:'Послушайте окончания на целых словах. /s/ после глухих, /z/ после звонких и гласных, /ɪz/ после свистящих и шипящих. Сначала выделяем /ɪz/, затем остальные группы.',note:'Добавляем -s или -es. Когда предметов несколько, a / an не нужны: cats, dogs, boxes.'});
task('inventory','present','Meet the team',{source:'67-rule',prompt:'У команды есть свой код: ARE.',lines:['We are pupils.','You are pupils.','They are pupils.'],speech:'We are pupils. You are pupils. They are pupils.',note:'We — мы • You — вы / ты • They — они',teacher:'Покажите на себя с учеником (we), на ученика/группу (you), на карточки команды (they).'});
task('inventory','present','Open the grammar gate',{source:'67-rule',prompt:'Меняем порядок — задаём вопрос.',lines:['They are pupils.','Are they pupils?','They are not pupils.','Yes, they are. / No, they aren’t.'],speech:'They are pupils. Are they pupils? They are not pupils. Yes, they are. No, they aren’t.',note:'Вопрос: Are в начале. Отрицание: not после are.',teacher:'Сравните утверждение, вопрос и отрицание. Повторите с we и you.'});
task('inventory','present','Short codes',{source:'68-rule',author:false,prompt:'Сокращённые формы',lines:['We are = We’re','You are = You’re','They are = They’re','are not = aren’t'],speech:'We are. We’re. You are. You’re. They are. They’re. Are not. Aren’t.',note:'Апостроф отмечает пропущенные буквы.',teacher:'Прочитайте полную и короткую формы. Значение одинаковое.'});
for(const [q,opts,answer,hint] of [
 ['What’s your name?',['I’m eight.','My name is Alex.','I’ve got a ball.'],'My name is Alex.','Спрашивают имя.'],
 ['Where are you from?',['I’m from Great Britain.','I’m a pupil.','They are cats.'],'I’m from Great Britain.','From помогает спросить, откуда ты.'],
 ['Who is she?',['She’s got a doll.','She is my sister.','She is from America.'],'She is my sister.','Кто она тебе?'],
 ['What toys have you got?',['I’ve got two cars.','He is a doctor.','Yes, they are.'],'I’ve got two cars.','Назови игрушки.'],
 ['Are they pupils?',['He has got a ball.','They’re from Britain.','Yes, they are.'],'Yes, they are.','В коротком ответе тоже есть are.'],
 ['What is he?',['He is my brother.','He’s a pilot.','He is from Africa.'],'He’s a pilot.','В этом вопросе спрашивают о профессии.']
]) task('listen','choice','Listen and choose',{prompt:'Послушай вопрос. Выбери ответ.',speech:q,options:opts,answer,hint,listening:true,teacher:'Не открывайте текст до первой попытки. После CHECK попросите прочитать ответ вслух.'});
for(const [word,answer,icon] of [['cats','/s/','🐈'],['dogs','/z/','🐕'],['boxes','/ɪz/','📦'],['dolls','/z/','🪆'],['buses','/ɪz/','🚌'],['ducks','/s/','🦆']]) task('sounds','choice','Sort the signal',{prompt:'Послушай слово. Как звучит окончание?',speech:word,word,icon,options:['/s/','/z/','/ɪz/'],answer,hint:'Сравни со словами cats, dogs, boxes. Нажми на пример под группой.',teacher:'После ответа ребёнок читает слово. IPA не озвучивается синтезатором; кнопки примеров произносят только целые слова.'});
for(const [text,answer] of [['I’ve got an aunt. … aunt is a doctor.','my'],['You’ve got a son. Is … son a pilot?','your'],['She has got a sister. … sister isn’t a pupil.','her']]) task('team','choice','Complete the file',{source:'66-9',author:false,prompt:'9. Спишите, вставляя пропущенные слова.',text,options:['my','your','her'],answer,hint:'I → my • you → your • she → her',teacher:'Выбор не проверяется до CHECK. После проверки прочитайте предложение целиком и по желанию запишите.'});
task('team','oral','Family channel /ɔː/',{source:'66-8',author:false,prompt:'8. Научись читать эти слова и предложения.',text:'or, your, daughter, a daughter — daughters, cosmonaut, a cosmonaut — cosmonauts, a sister or a brother, a son or a daughter, his daughter, He has got a daughter. His daughter is a doctor. Is he a pilot or a cosmonaut? He is a cosmonaut.',speech:'Or. Your. Daughter. A daughter. Daughters. Cosmonaut. A cosmonaut. Cosmonauts. A sister or a brother. A son or a daughter. His daughter. He has got a daughter. His daughter is a doctor. Is he a pilot or a cosmonaut? He is a cosmonaut.',teacher:'Выберите 2–3 строки для чтения вслух, остальные оставьте для повторения. Обратите внимание на /ɔː/.'});
task('team','oral','Family channel /ɑː/',{source:'66-8',author:false,prompt:'8. Научись читать эти слова и предложения.',text:'are, father, grandfather, aunt, they are, we are, We are from Great Britain. Sam and Sally are from Africa; my father, My father is a pilot; his grandfather, Has he got a grandfather? Yes, he has; her aunt, Her aunt isn’t a driver, she is a doctor.',speech:'Are. Father. Grandfather. Aunt. They are. We are. We are from Great Britain. Sam and Sally are from Africa. My father. My father is a pilot. His grandfather. Has he got a grandfather? Yes, he has. Her aunt. Her aunt isn’t a driver, she is a doctor.',teacher:'Прочитайте слова с /ɑː/ британского варианта. Выберите 2–3 фразы. Синтез может отличаться по акценту.'});
task('break','break','Agent, recharge!',{source:'68-4',prompt:'Повторяй за роботом. Потом дай команду учителю.',speech:'Let’s jump! Let’s run! Let’s play!',teacher:'Бег — только на месте. Движения по возможности ребёнка. Затем ученик сам приглашает учителя. Переход вручную.'});
task('code','words','Build 5 words',{source:'64-11',author:false,prompt:'11. Составь 5 слов из данных букв. Напиши и прочитай их.',letters:['w','a','m','n','y','e','n','A'],hint:'Можно составить имя Ann, местоимение или слово «имя». Буквы снова доступны для каждого нового слова.',teacher:'Задание открытое. Возможны name, my, Ann, am, we и другие. Словарь принимает 5 разных знакомых слов; учитель может подтвердить другие корректные решения. Буквы можно повторно использовать для следующего слова.',answer:'Например: name, my, Ann, am, we.'});
for(const [word,source,i] of [['have','64-12',0],['what','64-12',1],['where','64-12',2],['who','64-12',3],['family','64-12',4],['and','67-10',5],['yes','67-10',6],['friend','67-10',7],['hello','67-10',8],['cosmonaut','67-10',9]]) task('code','spell','Spelling terminal',{source,author:true,prompt:`${source==='64-12'?'12':'10'}. Запомни, как пишутся эти слова.`,speech:word,answer:word,hint:`Первая буква: ${word[0]}. Всего букв: ${word.length}.`,bonus:![0,2,7].includes(i),teacher:'Авторская проверка написания слов из указанного упражнения. Послушать → написать → CHECK → прочитать. Остальные слова доступны как бонусы.'});
task('code','notebook','Paper backup',{source:'64-11',prompt:'Запиши в тетрадь свои 5 собранных слов и два слова из Spelling terminal.',teacher:'Проверьте запись в тетради, затем подтвердите. Автоматической оценки почерка нет.'});
task('code','crossword','Crossword 13',{source:'64-13',author:false,prompt:'13. Разгадай кроссворд.',cross:'first',bonus:true,hint:'1 — семь букв. Вопросительное слово 4 имеет пять букв; проверь пересечения.',answer:'1 brother ↓ • 2 he → • 3 she → • 4 where →',teacher:'Сетка точно повторяет фото: brother вертикально, he пересекается на h, she на e, where на r. Подсказка 4 допускает разные слова, но сетка требует where.'});
task('code','crossword','Crossword 11',{source:'67-11',author:false,prompt:'11. Разгадай кроссворд.',cross:'second',bonus:true,hint:'1 — профессия из девяти букв. Слово 3 состоит из четырёх букв.',answer:'1 cosmonaut ↓ • 2 son → • 3 what →',teacher:'Сетка точно повторяет фото: cosmonaut вертикально, son на третьей букве s, what на седьмой букве a.'});
for(const [prompt,answer] of [['Собери сообщение: «Мы ученики».','We are pupils.'],['Задай вопрос: «Вы пилоты?»','Are you pilots?'],['Скажи: «Они не врачи».','They are not doctors.']]) task('grammar','build','Unlock the gate',{source:'67-rule',prompt,answer,tokens:answer.split(' '),hint:'Утверждение: кто + are. Вопрос: Are + кто. Отрицание: are not.',teacher:'Слова можно перетаскивать или выбирать нажатием. CHECK проверяет порядок.'});
task('grammar','match','Connect short codes',{source:'68-rule',prompt:'Соедини полные и короткие формы.',pairs:[['we are','we’re'],['you are','you’re'],['they are','they’re'],['are not','aren’t']],answer:'we are — we’re; you are — you’re; they are — they’re; are not — aren’t',hint:'Апостроф заменяет пропущенные буквы.',teacher:'Все четыре пары проверяются только после CHECK.'});
task('grammar','choice','Send a short answer',{prompt:'Are they pupils? Ответь «Да».',options:['Yes, they are.','Yes, they is.','No, they aren’t.'],answer:'Yes, they are.',hint:'They сочетается с are.',teacher:'Попросите прочитать короткий ответ.'});
task('grammar','choice','Send a short answer',{prompt:'Are they doctors? Ответь «Нет».',options:['No, they isn’t.','Yes, they are.','No, they aren’t.'],answer:'No, they aren’t.',hint:'Are not можно сократить до aren’t.',teacher:'Попросите прочитать короткий ответ.'});
task('production','production','Your team. Your story.',{source:'68-3',prompt:'Выбери двух персонажей и создай свою команду.',teacher:'Ученик выбирает карточки. Учитель задаёт вопросы, не читая за ребёнка: Who are they? What are they? Where are they from? What has he/she got? Затем ученик самостоятельно рассказывает о команде и своих игрушках. Подтвердите только после рассказа.',hint:'They are…|They are from…|He/She has got…|I’ve got…|I like to play with…'});
task('production','exchange','Switch roles!',{source:'68-3',prompt:'Теперь другая команда у учителя. Задай минимум 3 вопроса и пригласи поиграть.',teacher:'Пока карточки скрыты, ученик задаёт минимум три вопроса. Учитель видит секретную команду в этой панели и отвечает. Затем откройте карточки и сравните. Завершите приглашением Let’s play! Отметки вопросов ведёт учитель.',hint:'Who are they?|What are they?|Where are they from?|What has he/she got?',answer:'Команда учителя: Mia — doctor, Canada, two dolls. Ben — pilot, Canada, three cars.'});
task('final','oral','Transmission 01 / Read',{prompt:'Прочитай вопрос вслух.',text:'Where is your family from?',teacher:'Сначала без LISTEN и подсказок. Можно затем предложить ответить на вопрос. Подтвердите самостоятельное чтение.',final:true});
task('final','oral','Transmission 02 / Name',{prompt:'Назови несколько предметов по-английски.',illustrations:['🐈 🐈','🐕 🐕 🐕','📦 📦'],teacher:'Ожидаем cats, dogs, boxes, можно с числами. Не показывайте ответы до попытки.',answer:'two cats • three dogs • two boxes',final:true});
task('final','oral','Transmission 03 / Speak',{prompt:'Расскажи о своей команде и задай учителю вопрос.',teacher:'Самостоятельные 3–5 фраз и один вопрос. Подтвердите ответ; сайт не оценивает произношение.',final:true});
const VALID_WORDS=['a','an','am','Ann','name','my','we','me','man','men','many','any','new','may','way','yam','wan','Wayne'];
if(typeof module!=='undefined')module.exports={TASKS,SEGMENTS,MODULES,CROSSWORDS,VALID_WORDS,SOURCES};
